services:
  - type: web
    name: my-react-app
    env: static
    region: <your-region>          # e.g. us-central
    staticPublishPath: /build      # path to your React build folder
    routes:
      - type: rewrite
        source: /.*
        destination: /index.html
